### ISSUE TITLE
How to execute tests on a real device?

### ISSUE THREAD

**Issue by freynaud** [ios-driver/ios-driver#3]
Hello François,

at first you do a great job here in helping iOS testers to get rid of Automation as primary interface for testing on iOS. Adding a more familar abstraction level with the Selenium FW is such an improvement especially for the integration into an already existing Java/Eclipse test environment. Thanks a lot for that!

But lets get to the point: Because of the missing documentation it's not really clear to me how to exectue a test on a real device. For testing a web app on an iOS device with Selenium i needed the web driver app which handled the app on the remote device over a network connection. Due to the mapping of Selenium requests to UIAutomation actions there's no "remote handler" on the device for that will be done by Automation.

The main question is: How do it tell the ios-driver that he should use the USB connected device for testing instead of the app on the local machine? I thought it would be similar to testing on the emulator but obviously it's not :)
I built the app with Intstruments and targeted it to the connected device. Afterwards i copied the built app from "DerivedData" to a more comfortable directory, started the server with the app as input parameter and started the tests. To initialize the driver i used the following commands (as you stated in your example):

IOSCapabilities cap = IOSCapabilities.iphone("PatientSmartphoneApp", "1.0");
driver = new RemoteUIADriver(new URL("http://localhost:4444/wd/hub"), cap);

It would be great to hear from you as soon as possible.

Thanks in advance and nice greetings
Robert

**Comment by freynaud** [comment]
Hi Robert, 

There isn't support for real devices yet - Francois is working on it though and it's coming soon.

graham

**Comment by lukeis** [comment]
@rugh can you try with 0.6 and let us know how it goes?

**Comment by rugh** [comment]
Hey guys!
I tried it with 0.6. but got a similar error as the one mentioned in the google group (https://groups.google.com/forum/?fromgroups=#!topic/ios-driver/WAmDzWQ4HOw).

At first I started the server with the appropriate options:

``` bash
java -jar ios-server-0.7.0-SNAPSHOT.jar -beta -aut ~/Documents/dev/builds/device/InternationalMountains.app -port 4444
```

which leads to the following output in the terminal:

``` log
24:08:695 INFO ApplicationStore.<init>  App archive folder:/Users/Robert/Documents/tools/ios-driver/applications
loading lib /generated/libiosdriver.jnilib
24:09:984 INFO IOSServer.init  
Beta features enabled ( enabled by -beta flag ): true
Inspector: http://0.0.0.0:4444/inspector/
tests can access the server at http://0.0.0.0:4444/wd/hub
server status: http://0.0.0.0:4444/wd/hub/status
Connected devices: http://0.0.0.0:4444/wd/hub/devices/all
Applications: http://0.0.0.0:4444/wd/hub/applications/all
Capabilities: http://0.0.0.0:4444/wd/hub/capabilities/all
Monitoring '/Users/Robert/Documents/tools/ios-driver/applications' for new applications
using xcode install : /Applications/Xcode.app
using IOS version 6.1
Archived apps /Users/Robert/Documents/tools/ios-driver/applications
ios >= 6.0. Safari and hybrid apps are supported.

Applications :
--------------- 
    CFBundleName=,CFBundleVersion=1.1
    CFBundleName=Safari,CFBundleVersion=8536.25
    CFBundleName=Safari,CFBundleVersion=8536.25

2013-04-04 17:24:09.984:INFO::jetty-7.x.y-SNAPSHOT
2013-04-04 17:24:10.029:INFO::Started SelectChannelConnector@0.0.0.0:4444
24:10:964 INFO DeviceStore.onDeviceAdded  ADDED : iPhone4-CG,IOS 6.1.2[80eb295238cf5ceba798a2329c74a60dcf9e0a5f]
```

On the capabilities page:

``` log
InternationalMountain on iphone(Simulator)
{ "BuildMachineOSBuild": "12D78", "CFBundleDevelopmentRegion": "en", "CFBundleExecutable": "InternationalMountains", "CFBundleIconFile": "Icon.png", "CFBundleIdentifier": "InternationalMountain", "CFBundleInfoDictionaryVersion": "6.0", "CFBundlePackageType": "APPL", "CFBundleResourceSpecification": "ResourceRules.plist", "CFBundleSignature": "????", "CFBundleSupportedPlatforms": ["iPhoneOS"], "CFBundleVersion": "1.1", "DTCompiler": "", "DTPlatformBuild": "10B141", "DTPlatformName": "iphoneos", "DTPlatformVersion": "6.1", "DTSDKBuild": "10B141", "DTSDKName": "iphoneos6.1", "DTXcode": "0461", "DTXcodeBuild": "4H512", "LSRequiresIPhoneOS": true, "MinimumOSVersion": "6.1", "NSMainNibFile": "MainWindow", "UIDeviceFamily": [1], "applicationPath": "/Users/Robert/Documents/dev/builds/device/InternationalMountains.app", "device": "iphone", "deviceAlt": [ "iphone", "ipod" ], "device_Alt": [ "iphone", "ipad" ], "sdkVersion": "6.1", "sdkVersion_Alt": [ "5.0", "5.1", "6.0", "6.1" ], "simulator": true, "supportedLanguages": [ "zh", "fr", "en" ], "timeHack": false, "variation": "Regular" }
```

I guess this is the only interesting part of this page, whereupon two identical entries for "com.apple.mobilesafari on iphone(Simulator)" are shown. I don't know if this is on purpose, but it looks quite strange to me...

On the status page:

``` log
{
  "class": "org.openqa.selenium.remote.Response",
  "hCode": 579221443,
  "sessionId": null,
  "state": null,
  "status": 0,
  "value": {
    "build": {
      "revision": "0be3e889281c8ae1d4f08b9c38f65767075f512e",
      "time": "20130404-0955",
      "version": "0.7.0-SNAPSHOT"
    },
    "ios": {"simulatorVersion": "6.1"},
    "java": {"version": "1.7.0_15"},
    "os": {
      "arch": "x86_64",
      "name": "Mac OS X",
      "version": "10.8.3"
    },
    "supportedApps": [
      {
        "BuildMachineOSBuild": "12D78",
        "CFBundleDevelopmentRegion": "en",
        "CFBundleExecutable": "InternationalMountains",
        "CFBundleIconFile": "Icon.png",
        "CFBundleIdentifier": "InternationalMountain",
        "CFBundleInfoDictionaryVersion": "6.0",
        "CFBundlePackageType": "APPL",
        "CFBundleResourceSpecification": "ResourceRules.plist",
        "CFBundleSignature": "????",
        "CFBundleSupportedPlatforms": ["iPhoneOS"],
        "CFBundleVersion": "1.1",
        "DTCompiler": "",
        "DTPlatformBuild": "10B141",
        "DTPlatformName": "iphoneos",
        "DTPlatformVersion": "6.1",
        "DTSDKBuild": "10B141",
        "DTSDKName": "iphoneos6.1",
        "DTXcode": "0461",
        "DTXcodeBuild": "4H512",
        "LSRequiresIPhoneOS": true,
        "MinimumOSVersion": "6.1",
        "NSMainNibFile": "MainWindow",
        "UIDeviceFamily": [1],
        "applicationPath": "/Users/Robert/Documents/dev/builds/device/InternationalMountains.app",
        "device": "iphone",
        "deviceAlt": [
          "iphone",
          "ipod"
        ],
        "device_Alt": [
          "iphone",
          "ipad"
        ],
        "resources": {"CFBundleIconFile": "/wd/hub/resources/hash=-674408620"},
        "sdkVersion": "6.1",
        "sdkVersion_Alt": [
          "5.0",
          "5.1",
          "6.0",
          "6.1"
        ],
        "simulator": true,
        "supportedLanguages": [
          "zh",
          "fr",
          "en"
        ],
        "timeHack": false,
        "variation": "Regular"
      },
```

Additionally both MobileSafari Apps appear there but now with different "DTSDKName" entries for 6.1 and 6.0.

For the test I implemented the following setup function:

``` java
    @Before
    public void setup() throws MalformedURLException {
        IOSCapabilities cap = IOSCapabilities.iphone("InternationalMountains", "1.1");
        cap.setCapability(IOSCapabilities.SIMULATOR, false);
        cap.setCapability(IOSCapabilities.DEVICE, DeviceType.iphone);
        cap.setCapability(IOSCapabilities.UUID, "80eb295238cf5ceba798a2329c74a60dcf9e0a5f");
        //      cap.setLanguage("zh-Hant");
        driver = new RemoteIOSDriver(new URL("http://localhost:4444/wd/hub"), cap);
        driver.logElementTree(new File("test.png"), false);
    }
```

The test itself is not important due to the fact that it is never reached...Iam confronted with the following stacktrace instead:

``` stacktrace
org.openqa.selenium.SessionNotCreatedException: {simulator=false, timeHack=false, variation=Regular, locale=en_GB, CFBundleName=InternationalMountains, device=iphone, CFBundleVersion=1.1, language=en, uuid=80eb295238cf5ceba798a2329c74a60dcf9e0a5f} not found on server.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.7.0_15'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.7.0_15'
Driver info: driver.version: unknown
Command duration or timeout: 125 milliseconds
Build info: version: '2.31.0', revision: '1bd294d185a80fa4206dfeab80ba773c04ac33c0', time: '2013-02-27 13:51:26'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.7.0_15'
Driver info: org.uiautomation.ios.client.uiamodels.impl.RemoteIOSDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:187)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:151)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:216)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:111)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:129)
    at org.uiautomation.ios.client.uiamodels.impl.RemoteIOSDriver.<init>(RemoteIOSDriver.java:73)
    at de.tine.MyTest.setup(MyTest.java:49)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
```

I would be glad to get any useful hints. Thanks in advance!

Nice greetings
Robert

**Comment by nicegraham** [comment]
Hi Robert,

I think the problem is you have the app available for simulator but not a real device - I haven't been looking at real devices to be honest so @freynaud would have to confirm but _I think_ you'll have to deploy the application onto the iphone and before it will be available to use. If that's the case I'm sure there are plans to make that more automated and deploy to the device as part of the initialisation.

have a try and let us know! 

graham

**Comment by rugh** [comment]
Hey Graham,

thank you for the fast response! I deployed the App as described in the documentation via the UI using Instruments which immediatly deployed and started the app on the iPhone after it was built successfully. (Btw: I also wondered why the app was shown with the "(Simulator)" addition on the capabilities page)

I gave the CI a try for building the App and used a tool called fruitstrap for the deployment to the device (https://github.com/richardwhiuk/fruitstrap). Both steps worked as expected but the exception is still present. I have absolutely no idea what the problem could be...

BUT: I've got another question :P
Why is the built app needed for the launch of the server?

Nice greetings
Robert

**Comment by nicegraham** [comment]
Hi Robert, 

So the app is deployed on the iphone and you can see it in the capabilities but it still won't launch? If so can you give us a copy of the output from the /status and capabilities/all pages?

In terms of CI - we've had good success albeit on simulators. Our intention is to use the simulators for CI to have as high concurrency as possible. We're building the app in Jenkins and deploying it to a shared folder which we monitor using the -folder option.
http://ios-driver.github.io/ios-driver/setup.html#cli
When a new file is dropped there ios-driver picks it up and registers it on our grid. This is all working for us but as I said we're not currently using physical devices. 

The server doesn't need the app to start though it won't have any capabilities that way unless you do something like use the folder monitor function. The server will also pick up new devices which connect when it's running so there's no prerequisite to have the app built to launch the server there either.

**Comment by nicegraham** [comment]
I grabbed a device this afternoon and gave your scenario a try. Despite having the app installed on the device it didn't appear in the capabilities until I loaded the devices page and clicked archive on the application. It's probably not completely intuitive but you can click "ARCHIVE" below the application name on:
http://localhost:5555/wd/hub/devices/all

It should look like: 
![realdevicearchive](https://f.cloud.github.com/assets/1862480/349127/52cecf5a-9fa9-11e2-8e82-5a3429cea775.png)

At that point the application became available on the capabilities page:
https://gist.github.com/nicegraham/5331438

I launched the server and ran your example from above 
https://gist.github.com/nicegraham/5331534

and everything worked as expected, server output:
https://gist.github.com/nicegraham/5331525

and the screenshot
![test](https://f.cloud.github.com/assets/1862480/349141/9c09d362-9faa-11e2-9de5-7c5fc8334920.png)

**Comment by rugh** [comment]
You did it! That was exactly the missing part in the hole scenario! But as you mentioned it, this step is not really intuitive, however it worked eventually!

Thanks a lot for your great and persistent support!

(Next step on the pipeline: automate the hole process from building the app up to running the tests!)

I would suggests a closing of the issue.

**Comment by nicegraham** [comment]
Hi Robert, 

glad it worked out for you. I spoke to @freynaud about this and you don't _have_ to archive though you will need to have access to the application on you local drive somewhere which ios-driver can access. I've added some docs for real devices which we'll bring more up to date with the other options. http://ios-driver.github.io/ios-driver/setup.html#real

Keep in touch with with how you get on in the ios-driver forums. 

cheers,
Graham

**Comment by asabhijitshelar** [comment]
Hi,

Any way to execute it on ipad simulator

DesiredCapabilities cap = DesiredCapabilities.ipad();
    cap.setCapability(IOSCapabilities.BUNDLE_NAME,"InternationalMountains");
    cap.setCapability(IOSCapabilities.BUNDLE_VERSION,"1.1");
    cap.setCapability(CapabilityType.BROWSER_NAME, "ios");  
    cap.setCapability(CapabilityType.PLATFORM, "MAC");  
    cap.setCapability(IOSCapabilities.DEVICE, DeviceType.ipad);
    cap.setCapability(IOSCapabilities.SIMULATOR, true);
    //cap.setCapability("app","/Users/mac/Projects/InternationalMountains.app");
    // start the application
    driver = new RemoteWebDriver(new URL("http://192.168.1.28:5555/wd/hub"), cap);

It gives same error

I have started java -jar ios-server-standalone-0.6.6-SNAPSHOT.jar -aut InternationalMountains.app on mac machine

I need to start ipad simulator on mac machine
